<?php
defined('ABSPATH') or die("Jog on!");

	/*

	PLEASE DO NOT EDIT THIS FILE DIRECTLY

	Please modify via Admin > Tools > Settings > Weight Loss Tracker

	 */

	// -----------------------------------------------------------------------------------
	// Define whether Imperial and Units
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-units') || 'kg' == get_option('ws-ls-units'))	{
		define('WE_LS_DATA_UNITS', 'kg');
		define('WE_LS_IMPERIAL_WEIGHTS', false);
	}	else	{
		define('WE_LS_DATA_UNITS', get_option('ws-ls-units'));
		define('WE_LS_IMPERIAL_WEIGHTS', true);
	}

	// -----------------------------------------------------------------------------------
	// Define if target weights enabled
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-allow-targets') || 'no' == get_option('ws-ls-allow-targets')) {
		define('WE_LS_ALLOW_TARGET_WEIGHTS', false); }
	else {
		define('WE_LS_ALLOW_TARGET_WEIGHTS', true);
	}

	// -----------------------------------------------------------------------------------
	// Plot points on graph?
	// -----------------------------------------------------------------------------------
	if ('no' == get_option('ws-ls-allow-points')) {
		define('WE_LS_ALLOW_POINTS', false); }
	else {
		define('WE_LS_ALLOW_POINTS', true); }

	// -----------------------------------------------------------------------------------
	// Define whether to use tabs
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-use-tabs') || 'yes' == get_option('ws-ls-use-tabs')) {
			define('WE_LS_USE_TABS', true); }
	else {
		define('WE_LS_USE_TABS', false);
	}
	// -----------------------------------------------------------------------------------
	// Disable plugin CSS
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-disable-css') || 'no' == get_option('ws-ls-disable-css')) {
			define('WE_LS_CSS_ENABLED', true); }
	else {
			define('WE_LS_CSS_ENABLED', false);
	}

	// -----------------------------------------------------------------------------------
	// Define whether to support Avada theme
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-support-avada') || 'no' == get_option('ws-ls-support-avada')) {
		define('WE_LS_SUPPORT_AVADA_THEME', false); }
	else {
		define('WE_LS_SUPPORT_AVADA_THEME', true); }

	// -----------------------------------------------------------------------------------
	// Line Colours
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-target-colour') || 'no' == get_option('ws-ls-target-colour')) {
		define('WE_LS_TARGET_LINE_COLOUR', '#76bada'); }
	else {
		define('WE_LS_TARGET_LINE_COLOUR', get_option('ws-ls-target-colour')); }

	if (false == get_option('ws-ls-line-colour') || 'no' == get_option('ws-ls-line-colour')) {
		define('WE_LS_WEIGHT_LINE_COLOUR', '#dcdcdc'); }
	else {
		define('WE_LS_WEIGHT_LINE_COLOUR', get_option('ws-ls-line-colour')); }


	if (false == get_option('ws-ls-line-fill-colour') || 'no' == get_option('ws-ls-line-fill-colour')) {
		define('WE_LS_WEIGHT_FILL_COLOUR', '#f9f9f9'); }
	else {
		define('WE_LS_WEIGHT_FILL_COLOUR', get_option('ws-ls-line-fill-colour'));}


	// -----------------------------------------------------------------------------------
	// UK or US date?
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-use-us-dates') || 'uk' == get_option('ws-ls-use-us-dates')){
		define('WE_LS_US_DATE', false);}
	else {
		define('WE_LS_US_DATE', true); }


	// TODO: Move into settings page, etc for version 3.0
	define('WE_LS_CHART_TYPE', 'line'); //line, bar
	define('WS_LS_USE_DECIMALS', false);
	define('WE_LS_CHART_MAX_POINTS', 25);
	define('WE_LS_CHART_HEIGHT', 250);
	define('WE_LS_CHART_BEZIER_CURVE', true);
	define('WE_LS_CHART_POINT_SIZE', 3);
	define('WE_LS_CHART_SHOW_GRID_LINES', true);
	define('WE_LS_USE_MINIFIED_SCRIPTS', true);
	// -----------------------------------------------------------------------------------------
	// AC: Other defined fields that can't be changed in settings page.
	// -----------------------------------------------------------------------------------------

	define('WE_LS_TITLE', "Weight Loss Tracker");
	define('WE_LS_SLUG', "weight-loss-tracker");
	define('WE_LS_TABLENAME', "WS_LS_DATA");
	define('WE_LS_TARGETS_TABLENAME', "WS_LS_DATA_TARGETS");
	define('WE_LS_VERSION', "WS_LS_VERSION");
	define('WE_LS_CACHE_ENABLED', true);
	define('WE_LS_CACHE_TIME', 15 * MINUTE_IN_SECONDS ); // HOUR_IN_SECONDS
	define('WE_LS_CACHE_KEY_TARGET', "target-data");
	define('WE_LS_CACHE_KEY_DATA', "weight-data");
	define('WE_LS_CACHE_KEY_MIN_MAX_DATES', "min-max-dates");
	define('WE_LS_CACHE_KEY_TARGET_WEIGHT', "target-weight");
	define('WE_LS_CACHE_KEY_WEIGHT_EXTREME', "weight-extreme-");
	define('WE_LS_TABLE_MAX_WEEK_FILTERS', 100);
