theme: jekyll-theme-minimal
title: Weight Tracker Documentation
description: Documentation and tips for setting up Weight Tracker on your WordPress site.
baseurl: /
logo: assets/images/product-logo.png
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
port: 8000