name: Zip and FTP #3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: /home/runner/work/Weight-Tracker/Weight-Tracker/weight-loss-tracker/weight-loss-tracker/
    - name: Create dir
      run: |
          mkdir /tmp/zip/ 
    - name: Create code dir
      run: |
          mkdir /tmp/code/       
    - name: Copy files from repo
      run: rsync -av /home/runner/work/Weight-Tracker/Weight-Tracker/weight-loss-tracker/ /tmp/code/weight-loss-tracker/ --exclude thefoldertoexclude
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        directory: /tmp/code/
        filename: '/tmp/zip/weight-tracker.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig /playwright* /docs* /dist*'
    - name:  Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_URL }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: /tmp/zip/ 
