name: ftp-deploy
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build plugin # Remove or modify this step as needed
      run: |
        composer install --no-dev
        npm install
        npm run build

    - name: Generate zip
      uses: 10up/action-wordpress-plugin-build-zip@stable

      
      #  server: ${{ secrets.FTP_URL }}
     #  username: ${{ secrets.FTP_USERNAME }}
     #   password: ${{ secrets.FTP_PASSWORD }}

